Improvements for mercury driver
SiLab-Bonn/basil pull request #213
Opened 2024-04-02 15:19 UTC by SilasM2001

2024-04-22 11:40 UTC, YannickDieter commented
Please rebase to check if pipeline is now working.

2024-05-08 12:54 UTC, YannickDieter requested changes
Looks good to me, except the minor comments. In general it would also be good to change to [str.format](https://docs.python.org/3/library/stdtypes.html#str.format).

2024-05-08 12:54 UTC, YannickDieter commented on basil/HL/mercury.py
> +                print("At position", pos, "Traget at", value)
Super picky, but here is a typo ;)

2024-05-08 12:54 UTC, YannickDieter commented on basil/HL/mercury.py
> +            pos = self._wait_FE(address)
can we please change "FE" to something more meaningful?

2024-05-08 12:54 UTC, YannickDieter commented on basil/HL/mercury.py
> +                print("Warning: Precision not reached")
Same as above

2024-05-08 12:54 UTC, YannickDieter commented on basil/HL/mercury.py
> +                print("Warning: Precision not reached")
Should be something like: "Target not reached", no? Maybe one could print the target, actual value, and prec, too.

2024-05-10 11:25 UTC, YannickDieter commented
Thanks for the update. Actually we still should replace the `prints` with proper loggers like it is done for example [here](https://github.com/SiLab-Bonn/basil/blob/9982f223891680d8d6d68315f8b651f1e3405b30/basil/HL/sram_fifo.py#L8)

2024-05-16 08:01 UTC, cbespin commented on basil/HL/mercury.py
> +            if a == b:
Is this precise enough? I assume, some tolerance like one per mill might be good to account for numeric inaccuracies? Just wondering as this is typically the case for such that things.

2024-05-17 08:41 UTC, YannickDieter approved these changes

2024-05-17 08:55 UTC, cbespin commented
Since quite some lines are added that are not (can not?) be covered by tests, the coverage decreases, but we should ignore that.

2024-05-17 09:20 UTC, YannickDieter commented
Yeah, this was also my thought. So lets merge ;)

2024-05-17 09:21 UTC, merged